### ISSUE TITLE
error using cdk-dynamo-table-viewer

### ISSUE THREAD

**Issue by pankaj200788** [aws-samples/aws-cdk-intro-workshop#115] opened 2020-01-13 10:45 UTC
### What is the problem?

error while installing cdk-dynamo-table-viewer and unable to cdk diff later

### Reproduction Steps

```
source .env/bin/activate

pip install dk-dynamo-table-viewer

cdk diff
```

### Verbose Log
```
aws-cdk-region-info 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-cx-api 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-core 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-ssm 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-sqs 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-sns 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-sns-subscriptions 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-s3 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-s3-assets 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-route53 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-logs 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-lambda 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-kms 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-iam 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-events 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-elasticloadbalancingv2 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-ec2 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-dynamodb 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-cloudwatch 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-cloudformation 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-certificatemanager 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-autoscaling-common 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-applicationautoscaling 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-aws-apigateway 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
aws-cdk-assets 1.20.0 has requirement jsii~=0.21.1, but you'll have jsii 0.20.11 which is incompatible.
Installing collected packages: jsii, cdk-dynamo-table-viewer
  Found existing installation: jsii 0.21.1
    Uninstalling jsii-0.21.1:
      Successfully uninstalled jsii-0.21.1
Successfully installed cdk-dynamo-table-viewer-3.1.0 jsii-0.20.11
```

### Environment

  - **CDK CLI Version:** 1.20.0 (build 021c521)
  - **Section:** USING CONSTRUCT LIBRARIES
  - **Browser:** all
  - **Language:** Python

**Comment by NGL321** [comment] 2020-02-18 20:36
Hi @pankaj200788,

This strikes me as an installation issue and I could not reproduce the error myself.
Try starting the process from scratch and make sure that the CDK and all dependencies are installed on the same day (its possible that if you installed the CDK and the Dynamodb library at different times they were different versions).

Thanks for reporting!
😸

**Comment by SomayaB** [comment] 2020-03-16 20:53
Closing this issue since there hasn't been a response in a while. Feel free to reopen.

**Closed by SomayaB** 2020-03-16 20:53 UTC
Labels: bug, closing-soon, language/python, p1

**Comment by eferley** [comment] 2020-12-19 21:29
Hello, I think I hit the same kind of **Amazon.JSII.Runtime version conflict** today with **dotnet CDK** : 


```
$ dotnet add package Eladb.DynamoTableViewer --version 3.1.2
  Determining projects to restore...
  Writing /tmp/tmpe7gSlB.tmp
info : Adding PackageReference for package 'Eladb.DynamoTableViewer' into project '~/Dev/AWS/cdk-workshop/src/CdkWorkshop/CdkWorkshop.csproj'.
info : Restoring packages for ~/Dev/AWS/cdk-workshop/src/CdkWorkshop/CdkWorkshop.csproj...
error: NU1107: Version conflict detected for Amazon.JSII.Runtime. Install/reference Amazon.JSII.Runtime 1.15.0 directly to project CdkWorkshop to resolve this issue. 
error:  CdkWorkshop -> Amazon.CDK.AWS.SQS 1.79.0 -> Amazon.JSII.Runtime (>= 1.15.0 && < 2.0.0)
error:  CdkWorkshop -> Eladb.DynamoTableViewer 3.1.2 -> Amazon.JSII.Runtime (>= 0.21.1 && < 0.22.0).
info : Package 'Eladb.DynamoTableViewer' is compatible with all the specified frameworks in project '~/Dev/AWS/cdk-workshop/src/CdkWorkshop/CdkWorkshop.csproj'.
info : PackageReference for package 'Eladb.DynamoTableViewer' version '3.1.2' added to file '~/Dev/AWS/cdk-workshop/src/CdkWorkshop/CdkWorkshop.csproj'.
info : Committing restore...
info : Assets file has not changed. Skipping assets file writing. Path: ~/Dev/AWS/cdk-workshop/src/CdkWorkshop/obj/project.assets.json
log  : Failed to restore ~/Dev/AWS/cdk-workshop/src/CdkWorkshop/CdkWorkshop.csproj (in 122 ms).
```
