### ISSUE TITLE
Cookies approval won't go away

### ISSUE THREAD

**Issue by HeskethGD** [aws-samples/aws-cdk-intro-workshop#427] opened 2022-02-10 16:59 UTC
### What is the problem?

Trying to follow the CDK workshop here https://cdkworkshop.com/15-prerequisites.html and no matter what preferences I set for the cookies the approval banner wont go away and comes back every time I try and turn the page. It covers half the screen and makes the workshop unusable.

### Reproduction Steps

Visit the website. Select cookie preferences so banner goes away. Turn the page in the workshop. See the cookie banner come back.

### Browser

Chrome

**Comment by jpbarto** [comment] 2022-03-25 09:56
This same bug is hitting me as well.  Every page I go to in the workshop requires clicking 'Accept'  It's annoying.

**Comment by peterwoodworth** [comment] 2022-06-16 21:47
What internet browsers are you using? I'm not able to reproduce this on a couple different browsers.

**Comment by HeskethGD** [comment] 2022-06-16 23:20
Chrome
Version 102.0.5005.115 (Official Build) (64-bit)

**Comment by peterwoodworth** [comment] 2022-06-16 23:24
Do you have any sort of settings on regarding cookies? I can't even get the banner to appear on multiple devices and fresh browser installs. Mostly have been trying on Chrome around the same version as you

**Comment by hereticaljavascripter** [comment] 2022-08-19 13:24
occurs for me on: 
Chrome Version 104.0.5112.81 (Official Build) (64-bit) (and another version on work laptop)
Edge Version 104.0.1293.54 (Official build) (64-bit)

doesn't occur for me on:
Internet Explorer Version 21H2 (OS Build 19044.1889) (the cookie notice doesn't show up at all)

then it gets interesting, on Opera 89.0.4447.83 it occurs if VPN is in asia or europe, but in the americas I don't see cookie notice at all

**Comment by peterwoodworth** [comment] 2022-08-29 21:27
I wasn't able to reproduce this originally, but we've just made a change to our website and have specified that we don't have cookies. Hopefully this will fix things

I was never able to reproduce so I can't confirm if this is going to remove the approvals you guys are seeing, so I'm going to close this assuming the changes we've made have worked. Changes should be up now

**Closed by peterwoodworth** 2022-08-29 21:27 UTC
Labels: bug, effort/medium, p1
