### ISSUE TITLE
No instructions to tear down DynamoDB (during cleanup)

### ISSUE THREAD

**Issue by cyruc** [aws-samples/aws-cdk-intro-workshop#151] opened 2020-07-29 06:05 UTC
At the end of the workshop when we tear down the stack there are no instructions to delete DynamoDB. Folks using dev environments could potentially incur costs as a result. Might be a good idea to remind folks to wipe DynamoDB after they do cdk destroy.

**Comment by SomayaB** [comment] 2020-07-30 05:52
Duplicate of #126. Thanks for bringing our attention back to this issue.

**Closed** 2020-07-30 05:52 UTC
Labels: duplicate, feature-request
