### ISSUE TITLE
"jsii.errors.JSIIError: this.handler.addPermission is not a function" when deploying 

### ISSUE THREAD

**Issue by rajish** [aws-samples/aws-cdk-intro-workshop#101] opened 2019-12-19 08:11 UTC
### What is the problem?
In the step *Deploy* in the page https://cdkworkshop.com/30-python/40-hit-counter/400-use.html the following error appears making the progress of the workshop impossible:

```jsii.errors.JSIIError: this.handler.addPermission is not a function```

### Reproduction Steps
Follow the workshop using Python 3.7.5 and NodeJS 12.14.0

### Verbose Log
```08:57:18 [rajish:~/proj/cdkworkshop] [.env] master(+19/-16)* ± cdk deploy
jsii.errors.JavaScriptError:
  TypeError: this.handler.addPermission is not a function
      at LambdaIntegration.bind (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/integrations/lambda.js:30:22)
      at Method.renderIntegration (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/method.js:75:21)
      at Method.renderIntegration (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/method.js:70:29)
      at new Method (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/method.js:27:31)
      at RootResource.addMethod (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:17:16)
      at ProxyResource.addMethod (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:218:37)
      at new ProxyResource (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:209:35)
      at RootResource.addProxy (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/resource.js:20:16)
      at new LambdaRestApi (/private/var/folders/mx/g17hdwqx645gwbzh5_cfp4p40000gq/T/jsii-kernel-rL9mAe/node_modules/@aws-cdk/aws-apigateway/lib/lambda-api.js:19:23)
      at Kernel._wrapSandboxCode (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:8224:19)
      at Kernel._create (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7761:26)
      at Kernel.create (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7508:21)
      at KernelHost.processRequest (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7296:28)
      at KernelHost.run (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7236:14)
      at Immediate._onImmediate (/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_embedded/jsii/jsii-runtime.js:7239:37)
      at processImmediate (internal/timers.js:439:21)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    CdkworkshopStack(app, "cdkworkshop", env={'region': 'us-west-2'})
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/rajish/proj/cdkworkshop/cdkworkshop/cdkworkshop_stack.py", line 29, in __init__
    handler=hello_with_counter,
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_runtime.py", line 66, in __call__
    inst = super().__call__(*args, **kwargs)
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/aws_cdk/aws_apigateway/__init__.py", line 14026, in __init__
    jsii.create(LambdaRestApi, self, [scope, id, props])
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_kernel/__init__.py", line 229, in create
    interfaces=[iface.__jsii_type__ for iface in getattr(klass, "__jsii_ifaces__", [])],
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 333, in create
    return self._process.send(request, CreateResponse)
  File "/Users/rajish/proj/cdkworkshop/.env/lib/python3.7/site-packages/jsii/_kernel/providers/process.py", line 318, in send
    raise JSIIError(resp.error) from JavaScriptError(resp.stack)
jsii.errors.JSIIError: this.handler.addPermission is not a function
```

### Environment

  - **CDK CLI Version:** 1.19.0 (build 5597bbe)
  - **Section:** AWS CDK Intro Workshop > Python Workshop > Writing constructs > Use the hit counter
  - **Browser:** Chrome
  - **Language:** Python

**Comment by rajish** [comment] 2019-12-19 08:31
Further investigation narrowed the problem to replacing the code in `cdkworshop_stack.py` from:
```
        apigw.LambdaRestApi(
            self, 'Endpoint',
            handler=my_lambda,
        )
```
to
```
        apigw.LambdaRestApi(
            self, 'Endpoint',
            handler=hello_with_counter,
        )
```

This single line change causes the error.

**Comment by NGL321** [comment] 2019-12-21 01:19
> Further investigation narrowed the problem to replacing the code in `cdkworshop_stack.py` from:
> 
> ```
>         apigw.LambdaRestApi(
>             self, 'Endpoint',
>             handler=my_lambda,
>         )
> ```
> 
> to
> 
> ```
>         apigw.LambdaRestApi(
>             self, 'Endpoint',
>             handler=hello_with_counter,
>         )
> ```
> 
> This single line change causes the error.

Hi @rajish,

I'm sorry if I am missing something very obvious, but I dont see anywhere in the workshop where the first code is written. It should always be written either as `handler=hello` or `handler=hello_with_counter`.

Please let me know so I can get this fixed!

TIA 😸

**Comment by paulabenzar** [comment] 2019-12-24 12:21
The code in the example is wrong. The handler to the Api Gateway should be the lambda function not the construct.

**Comment by NGL321** [comment] 2020-03-03 23:24
Closing due to lack of follow-up (`hello_with_counter.handler` confirmed to be correct AND in the workshop).

**Closed by NGL321** 2020-03-03 23:24 UTC
Labels: bug, language/python, p1

**Comment by richardgroves** [comment] 2024-03-27 11:32
This good answer from @paulabenzar is now broken as page https://cdkworkshop.com/30-python/40-hit-counter/300-resources.html changes it to `_handler` to the correct fix is now:

`apigw.LambdaRestApi( self, 'Endpoint', handler=hello_with_counter._handler)`
