### ISSUE TITLE
Cleanup TS

### ISSUE THREAD

**Issue by mhausenblas** [aws-samples/aws-cdk-intro-workshop#126] opened 2020-02-22 12:35 UTC
## :rocket: Feature Request

In the [TS cleanup step](https://github.com/aws-samples/aws-cdk-intro-workshop/blob/master/workshop/content/20-typescript/60-cleanups/_index.md) one should mention that `cdk destroy` does not clean up everything, for example, the DynamoDB table, the S3 bucket, and the CDKToolkit CFN stack are still left over after the command has completed.

**Comment by NGL321** [comment] 2020-03-04 02:31
This is a good point. I will make sure an overview of removal policies and the CFN stack get added!

**Comment by peterwoodworth** [comment] 2022-06-14 00:36
Closing as duplicate of #276

**Closed by peterwoodworth** 2022-06-14 00:36 UTC
Labels: feature-request, effort/small, p1, in-progress
